name: Hello World
on: [workflow_dispatch]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-sheteng-test-codebuild-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World!"
